spring.application.name=portfolio

spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# NSE historical endpoint. Dates are generated for each scheduled run.
daily-price.api-url=https://www.nseindia.com/api/historicalOR/generateSecurityWiseHistoricalData?from={from}&to={to}&symbol={symbol}&type=priceVolumeDeliverable&series={series}&csv=true
daily-price.cron=0 0 16 * * MON-FRI
daily-price.zone=Asia/Kolkata


batch.historical-import.enabled=false
